export const FETCH_CARS_STARTED = 'FETCH_CARS_STARTED';
export const FETCH_CARS_SUCCEEDED = 'FETCH_CARS_SUCCEEDED';
export const FETCH_CARS_FAILED = 'FETCH_CARS_FAILED';

export const SAVE_CAR_SUCCEEDED = 'SAVE_CAR_SUCCEEDED';
export const SAVE_CAR_FAILED = 'SAVE_CAR_FAILED';
export const SAVE_CAR_STARTED = 'SAVE_CAR_STARTED';

export const DELETE_CAR_SUCCEEDED = 'DELETE_CAR_SUCCEEDED';
export const DELETE_CAR_FAILED = 'DELETE_CAR_FAILED';
export const DELETE_CAR_STARTED = 'DELETE_CAR_STARTED';

export const SET_PAGE = 'SET_PAGE';
export const SET_SEARCH = 'SET_SEARCH';